# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_auto_20180406_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dp',
            field=models.URLField(default='https://procurement.unl.edu/images/staff-photos/y_u_no_photo_Square.png', max_length=300),
        ),
    ]
