# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-07 01:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0004_auto_20180407_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 1, 30, 33, 540282, tzinfo=utc), verbose_name='date published'),
        ),
    ]
